# -*- coding: utf-8 -*-
"""Datopian.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w9fhjCDq1fo-jyu14oT__KbObm-Ak51p
"""

!pip install kora
from kora.selenium import wd

url = 'https://en.wikipedia.org/wiki/Road_safety_in_Europe'
wd.get(url)
wd.save_screenshot('screenshot.png');

import pandas as pd
tables = pd.read_html(wd.page_source)
tables[2]

from bs4 import BeautifulSoup

soup = BeautifulSoup(wd.page_source,"html.parser")
table = soup.find_all('table')[2]
rows = table.find_all('tr')
row_list = list()

for tr in rows:
    td = tr.find_all('td')
    row = [i.text for i in td]
    row_list.append(row)

df_bs = pd.DataFrame(row_list,columns=['Country','Area','Population','GDP per capita','Population density','Vehicle ownership','Road Network Length','Total road deaths','Road deaths per Million Inhabitants','Number of people Killed by billion','Number of seriously Injurled'])
df_bs.set_index('Country',inplace=True)
df_bs.drop(['Road Network Length','Number of people Killed by billion','Number of seriously Injurled'],  inplace=True, axis=1)
df_bs['Year'] = '2018'
df_bs.sort_values(by="Road deaths per Million Inhabitants",ascending=False,kind="mergesort")
df_bs.to_csv('test.csv')